# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [9.x, 10.x, 12.x]

    steps:
    - uses: actions/npm@master
    - name: Install dependencies and build the app
    - run: npm install
    - run: npm run build
    - uses: docker://circleci/node:8-browsers
    - name: Run integration tests
    - run: npm run e2e:github
